### PR TITLE
Weather App

### PR DESCRIPTION
**Pull request by nganifaith**
A weather app built using openweather API. This project implements a basic Api call to the openweather API it makes use of city, unit and appID when requesting data. 
The application made use of the following data from the API
-- Main City
-- Country Symbol
-- Date
-- Main temperature
-- Main Weather forecast and 
-- The minimum and maximum temperature for the day.

It gives you the ability to change the toggle between the unit of temperature measurement.

### CODE REVIEW

**Review by NtwaliHeritier — CHANGES_REQUESTED** [review]
### **STATUS: CHANGES REQUESTED🛑️🛑️**

Hello @nganifaith 
Great work on this project. The code looks clean, the repo looks professional. Congrats👏️👏️
However, let's make few changes and get it approved👍️👍️

[REQUIRED]: Background images should change with each new entry. Kindly implement the feature.
[REQUIRED]: The change unit button works perfectly, however it should be a toggle button. Kindly implement it.

That's it. Make the requested changes and ask for another review👍️👍️

Happy coding💻️💻️

**Comment by nganifaith** [comment]
> ### **STATUS: CHANGES REQUESTED🛑️🛑️**
> Hello @nganifaith
> Great work on this project. The code looks clean, the repo looks professional. Congrats👏️👏️
> However, let's make few changes and get it approved👍️👍️
> 
> [REQUIRED]: Background images should change with each new entry. Kindly implement the feature.
> [REQUIRED]: The change unit button works perfectly, however it should be a toggle button. Kindly implement it.
> 
> That's it. Make the requested changes and ask for another review👍️👍️
> 
> Happy coding💻️💻️

Hello, @NtwaliHeritier Thanks for the review, however, I will need more explanation on the points you've made,
> If you noticed from my readme file Dubai has a different background image from the home that is because the background image changes based on the weather condition. Can you explain which entry you are referring to in this case?
> For the button what is the advantage of using a toggle over the current implementation. 

Also, all of these requirements are not part of the project requirement on Odin so I see no reason why you are making them as required changes.

**Comment by NtwaliHeritier** [comment]
> > ### **STATUS: CHANGES REQUESTEDstop_signstop_sign**
> > Hello @nganifaith
> > Great work on this project. The code looks clean, the repo looks professional. Congratsclapclap
> > However, let's make few changes and get it approved+1+1
> > [REQUIRED]: Background images should change with each new entry. Kindly implement the feature.
> > [REQUIRED]: The change unit button works perfectly, however it should be a toggle button. Kindly implement it.
> > That's it. Make the requested changes and ask for another review+1+1
> > Happy codingcomputercomputer
> 
> Hello, @NtwaliHeritier Thanks for the review, however, I will need more explanation on the points you've made,
> 
> > If you noticed from my readme file Dubai has a different background image from the home that is because the background image changes based on the weather condition. Can you explain which entry you are referring to in this case?
> > For the button what is the advantage of using a toggle over the current implementation.
> 
> Also, all of these requirements are not part of the project requirement on Odin so I see no reason why you are making them as required changes.

Below is the screenshot from odin for both of the requirements from odin

appearance requirement: https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/appearance_requirement.png

toggle button requirement:
https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/search_requirement.png

**Comment by nganifaith** [comment]
> > > ### **STATUS: CHANGES REQUESTEDstop_signstop_sign**
> > > Hello @nganifaith
> > > Great work on this project. The code looks clean, the repo looks professional. Congratsclapclap
> > > However, let's make few changes and get it approved+1+1
> > > [REQUIRED]: Background images should change with each new entry. Kindly implement the feature.
> > > [REQUIRED]: The change unit button works perfectly, however it should be a toggle button. Kindly implement it.
> > > That's it. Make the requested changes and ask for another review+1+1
> > > Happy codingcomputercomputer
> > 
> > 
> > Hello, @NtwaliHeritier Thanks for the review, however, I will need more explanation on the points you've made,
> > > If you noticed from my readme file Dubai has a different background image from the home that is because the background image changes based on the weather condition. Can you explain which entry you are referring to in this case?
> > > For the button what is the advantage of using a toggle over the current implementation.
> > 
> > 
> > Also, all of these requirements are not part of the project requirement on Odin so I see no reason why you are making them as required changes.
> 
> Below is the screenshot from odin for both of the requirements from odin
> 
> appearance requirement: https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/appearance_requirement.png
> 
> toggle button requirement:
> https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/search_requirement.png

@NtwaliHeritier the requirement didn't specify a toggle button. it *toggle displaying the data* which I think I implemented perfectly. And for the background can you test it properly

**Review by GzimAsani — APPROVED** [review]
# STATUS: PROJECT ACCEPTED :green_circle: :partying_face: 

## Hello @nganifaith, thank you for making all the required changes. Your project looks complete now, feel free to merge it and continue in the next projects :+1: 

# HAPPY CODING :computer: :desktop_computer:

**Pull request merged**
